### ISSUE TITLE
The python runtime has an inflexible dependency on typeguard~=2.13.3

### ISSUE THREAD

**Issue by MatthewGrant** [cdklabs/awscdk-asset-kubectl#1186]
@mrgrain I'm looking for some help. This package specifically `aws-cdk.asset-kubectl-v20`  is a dependency of `aws-cdk-lib` for the python runtime. I'm trying to install a package that depends on a higher version of the currently pinned dependency `typeguard`. 

Can the v20 dependencies be bumped and released to include `"jsii>=1.103.1, <2.0.0"` to get the pacmak updates from this [PR](https://github.com/aws/jsii/pull/4611). I think `aws-cdk-asset-awscli-v1 v2.2.202` had the same issue but is now fixed in higher versions. [diff](https://github.com/cdklabs/awscdk-asset-awscli/compare/awscli-v1v2.2.202...awscli-v1v2.2.203#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R65)

```
# requirements.txt - py3.9
aws-cdk-lib==2.161.1
aws-cdk-asset-awscli-v1>2.2.202
typeguard>=4.0
```
```
pip install -r requirements.txt

ERROR: Cannot install -r requirements.txt (line 1), aws-cdk-lib and typeguard>=4.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested typeguard>=4.0
    aws-cdk-lib 2.161.1 depends on typeguard<5.0.0 and >=2.13.3
    aws-cdk-asset-awscli-v1 2.2.203 depends on typeguard<5.0.0 and >=2.13.3
    aws-cdk-asset-kubectl-v20 2.1.2 depends on typeguard~=2.13.3
```    

Please let me know if this isn't the place for this request, my understanding is incorrect, thanks.

**Comment by mrgrain** [comment]
Looking into if we can remove this dependency. Otherwise an upgrade should be possible.

**Comment by mrgrain** [comment]
New version is released.

**Comment by MatthewGrant** [comment]
Thank you!

**Comment by mrgrain** [comment]
> Thank you!

Let me know if that works!

**Comment by MatthewGrant** [comment]
> > Thank you!
> 
> Let me know if that works!

Yes, it worked! ~~however I tagged you in the constructs repo, I'm seeing the same issue there.~~
