### ISSUE TITLE
Feature Request: Asset with kubectl v1.25

### ISSUE THREAD

**Issue by CarlosDomingues** [cdklabs/awscdk-asset-kubectl#166]
Kubernetes v1.25 [is now supported by EKS](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.25).

Edit: I'm willing to contribute to this feature

**Comment by CarlosDomingues** [comment]
Yesterday I was able to follow the contributing guidelines and successfully deploy a [new version](https://github.com/CarlosDomingues/awscdk-asset-kubectl/commit/bd11160684b3c763bbacf40ee4320dcdc764cfe1) supporting kubectl v1.2.5 and Helm 3.10.3. Please let me know if we can turn this into a PR.

**Comment by kaizencc** [comment]
Thanks for opening the issue @CarlosDomingues! I've created the `kubectl-v25/main` branch [here](https://github.com/cdklabs/awscdk-asset-kubectl/tree/kubectl-v25/main). The next steps would be to continue following the steps outlined in the contributing [guide](https://github.com/cdklabs/awscdk-asset-kubectl/blob/kubectl-v24/main/CONTRIBUTING.md#contributing-a-new-kubectl-asset). Are you willing to do that? Or I can add it on to my list of things to do :).

**Comment by CarlosDomingues** [comment]
@kaizencc thanks! I completed the steps described on the guide last week and was waiting for the branch. Please find my PR [here](https://github.com/cdklabs/awscdk-asset-kubectl/pull/174).
