### ISSUE TITLE
Support EKS v1.26

### ISSUE THREAD

**Issue by aiell0** [cdklabs/awscdk-asset-kubectl#240]
EKS v1.26 was [just announced](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-26/). Would be good to have it rolled into CDK. Will also require making a change to [awscdk-asset-kubectl](https://github.com/cdklabs/awscdk-asset-kubectl) repo.

**Comment by kaizencc** [comment]
Thanks for the report. I did step 2 of our process and opened up the necessary branches: https://github.com/cdklabs/awscdk-asset-kubectl/blob/kubectl-v24/main/CONTRIBUTING.md#contributing-a-new-kubectl-asset. The rest is up to whoever feels comfortable contributing!

FYI corresponding helm version should be 3.11.

**Comment by robertd** [comment]
For some reason #242 didn't close this PR automatically.
