### ISSUE TITLE
Support EKS v1.27

### ISSUE THREAD

**Issue by pahud** [cdklabs/awscdk-asset-kubectl#284]
[Amazon EKS now supports Kubernetes version 1.27
](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-27/)

**Comment by fed-sv** [comment]
Any update on this please? :)

**Comment by isker** [comment]
This was done but the issue was never closed. https://www.npmjs.com/package/@aws-cdk/lambda-layer-kubectl-v27
