### ISSUE TITLE
Feature Request: Asset with kubectl v1.27

### ISSUE THREAD

**Issue by fed-sv** [cdklabs/awscdk-asset-kubectl#290]
Hi eks v1.27 is out and I need this to support it. 
Can you please do step 2 of your process and open up the necessary branches: https://github.com/cdklabs/awscdk-asset-kubectl/blob/kubectl-v24/main/CONTRIBUTING.md#contributing-a-new-kubectl-asset.

I'll be happy to create a PR for the change

**Comment by isker** [comment]
This was done but the issue was never closed: https://www.npmjs.com/package/@aws-cdk/lambda-layer-kubectl-v27
