### ISSUE TITLE
Support EKS 1.28

### ISSUE THREAD

**Issue by isker** [cdklabs/awscdk-asset-kubectl#437]
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-28/

**Comment by mperochon** [comment]
I'm just pushing a PR to add the 1.28 version :)

**Comment by mperochon** [comment]
Just in case, it seems it has a bug with the latest version of helm : https://github.com/aws/karpenter/issues/4724

Since we use this layer on production we got a lot of 400 error with the ecr regristry.

Maybe helm needs to be downgrade for the moment. What do you think guys ?

**Comment by robbiecooray1** [comment]
> Just in case, it seems it has a bug with the latest version of helm : [aws/karpenter#4724](https://github.com/aws/karpenter/issues/4724)
> 
> Since we use this layer on production we got a lot of 400 error with the ecr regristry.
> 
> Maybe helm needs to be downgrade for the moment. What do you think guys ?

Agree. Appears the update to revert is merged. https://github.com/helm/helm/pull/12527. Until this is released, 1.28 is blocked.

Better yet, make the helm version customisable so that there is flexibility to change.

**Comment by isker** [comment]
Looks like this is done.
