### ISSUE TITLE
V28 failed to publish Nuget package

### ISSUE THREAD

**Issue by ariciputi** [cdklabs/awscdk-asset-kubectl#470]
Hi,
[latest build](https://github.com/cdklabs/awscdk-asset-kubectl/actions/runs/6657389337) for v28 failed to publish Dotnet package to Nuget. Reading the logs seems an issue related to authentication against the Nuget repo, resulting in the package being available on all platform except Dotnet. Can you please have a look into this and fix it?

Thanks.

**Comment by mperochon** [comment]
Hi @ariciputi,

It seems fixed now :)

**Comment by ariciputi** [comment]
@mperochon great, thanks.
